### ISSUE TITLE
Make it work with latest version of node

### ISSUE THREAD

**Issue by amaurymartiny** [seanchas116/transparent-titlebar#1]
```javascript
  Error: The module '/Users/amaurymartiny/Workspace/light/node_modules/transparent-titlebar/build/Release/addon.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 64. This version of Node.js requires
  NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or `npm install`).
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
      at Object.Module._extensions..node (module.js:671:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at bindings (/Users/amaurymartiny/Workspace/light/node_modules/bindings/bindings.js:81:44)
      at Object.<anonymous> (/Users/amaurymartiny/Workspace/light/node_modules/transparent-titlebar/index.js:1:130)

```

**Comment by gorbypark** [comment]
I'm also facing this issue.

**Comment by measdot** [comment]
[This is expected behavior](https://electronjs.org/docs/tutorial/using-native-node-modules)

> Native Node modules are supported by Electron, but since Electron is very likely to use a different V8 version from the Node binary installed on your system, the modules you use will need to be recompiled for Electron.

```
npm install --save-dev electron-rebuild

# Every time you run "npm install", run this:
./node_modules/.bin/electron-rebuild

# On Windows if you have trouble, try:
.\node_modules\.bin\electron-rebuild.cmd`
```

**Comment by jhackett1** [comment]
Using `electron-rebuild` doesn't work for me either. It spits out a long error message about node-gyp, something about "too few arguments". No idea how to fix so using something else.

**Comment by seanchas116** [comment]
> Using electron-rebuild doesn't work for me either. It spits out a long error message about node-gyp, something about "too few arguments". No idea how to fix so using something else.

I fixed the node-gyp issue in the latest version (0.2.0) !
It now works with the latest Electron 9.2.0.

**Comment by seanchas116** [comment]
If the NODE_MODULE_VERSION issue happens, refer https://www.electronjs.org/docs/tutorial/using-native-node-modules.
